notifications:
  email:
    on_success: never
    on_failure: change

language: generic

os:
  - linux
  - osx

script:
  - bin/dotfiles

git:
  depth: 10

sudo: false

branches:
  only:
    - master
