name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-ref:
    name: Update master branch
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    runs-on:
      - ubuntu-latest
    steps:
      - name: Run GitHub script
        uses: actions/github-script@v3
        with:
          script: |
            github.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/master',
              sha: context.sha,
            })
