name: Update master branch

on:
  push:
    branches:
      - main

jobs:
  update-ref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - run: |
          git fetch origin
          git branch master origin/master
          git update-ref refs/heads/master "${GITHUB_SHA}"
          git push origin master
